### ISSUE TITLE
Using sqlite for the docker container not working

### ISSUE THREAD

**Issue by jkaberg** [cypht-org/cypht#1267]
## 💬 Question

I'm trying to run the docker container using sqlite as an database backend, while setting this up I noticed this [comment](https://github.com/cypht-org/cypht/issues/353#issuecomment-507773747) aswell as the comments in [database.php](https://github.com/cypht-org/cypht/blob/master/config/database.php) and configured the container accordingly like so

```
  cypht:
    image: cypht/cypht:2.4.0
    restart: unless-stopped
    depends_on:
      - stalwart
    volumes:
      - ${STORAGE_DIR}/mail/cypht/data:/var/lib/hm3
    environment:
      - AUTH_USERNAME=<secret>
      - AUTH_PASSWORD=<secret>
      - DB_CONNECTION_TYPE=socket
      - DB_DRIVER=sqlite
      - DB_SOCKET=/var/lib/hm3/db.sqlite
      - SESSION_TYPE=DB
      - USER_CONFIG_TYPE=DB
      - SMTP_SERVER=stalwart
      - SMTP_PORT=587
      - IMAP_SERVER=stalwart
      - IMAP_PORT=993
    networks:
      - traefik
```

However upon inspecting the logs the container is failing to start and I'm seeing:
```
cypht-1  |
cypht-1  | Attempting to connect to database ... (1/10)
cypht-1  | Attempting to connect to database ... (2/10)
cypht-1  | Attempting to connect to database ... (3/10)
cypht-1  | Attempting to connect to database ... (4/10)
cypht-1  | Attempting to connect to database ... (5/10)
cypht-1  | Attempting to connect to database ... (6/10)
cypht-1  | Attempting to connect to database ... (7/10)
cypht-1  | Attempting to connect to database ... (8/10)
cypht-1  | Attempting to connect to database ... (9/10)
cypht-1  | Attempting to connect to database ... (10/10)
cypht-1  | Unable to connect to database
cypht-1 exited with code 0
cypht-1  |
cypht-1  | Attempting to connect to database ... (1/10)
cypht-1  | Attempting to connect to database ... (2/10)
cypht-1  | Attempting to connect to database ... (3/10)
cypht-1  | Attempting to connect to database ... (4/10)
cypht-1  | Attempting to connect to database ... (5/10)
cypht-1  | Attempting to connect to database ... (6/10)
cypht-1  | Attempting to connect to database ... (7/10)
cypht-1  | Attempting to connect to database ... (8/10)
cypht-1  | Attempting to connect to database ... (9/10)
cypht-1  | Attempting to connect to database ... (10/10)
cypht-1  | Unable to connect to database
cypht-1  |
cypht-1  | Attempting to connect to database ... (1/10)
cypht-1  | Attempting to connect to database ... (2/10)
cypht-1  | Attempting to connect to database ... (3/10)
cypht-1  | Attempting to connect to database ... (4/10)
cypht-1  | Attempting to connect to database ... (5/10)
cypht-1  | Attempting to connect to database ... (6/10)
cypht-1  | Attempting to connect to database ... (7/10)
cypht-1  | Attempting to connect to database ... (8/10)
```

Am I missing something?

**Comment by jkaberg** [comment]
Sorry, my fault. Working config for sqlite:

```
  cypht:
    image: cypht/cypht:2.4.0
    restart: unless-stopped
    volumes:
      - ${STORAGE_DIR}/mail/cypht/data:/var/lib/hm3
    environment:
      - AUTH_USERNAME=<secret>
      - AUTH_PASSWORD=<secret>
      - DB_CONNECTION_TYPE=socket
      - DB_DRIVER=sqlite
      - DB_SOCKET=/var/lib/hm3/db.sqlite
      - SESSION_TYPE=DB
      - USER_CONFIG_TYPE=DB
      - SMTP_SERVER=server
      - SMTP_PORT=587
      - IMAP_SERVER=server
      - IMAP_PORT=993
```
