### ISSUE TITLE
💬 [Question] How to config LDAP auth

### ISSUE THREAD

**Issue by kevinend51** [cypht-org/cypht#1481]
## 💬 Question

I want to login cypht with my ldap server, here is my docker-compose.yml:

```
services:
  db:
    image: mariadb:10
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<db_root_password>
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=<db_password>
  cypht:
    image: cypht/cypht:2.4.0
    ports:
      - "50210:80"
    environment:
      - DB_CONNECTION_TYPE=host
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_NAME=cypht
      - DB_USER=cypht
      - DB_PASS=<db_password>
      - SESSION_TYPE=DB
      - USER_CONFIG_TYPE=DB
      - AUTH_TYPE=LDAP
      - LDAP_AUTH_PORT=50061
      - LDAP_AUTH_SERVER=<ldap_server_domain>
      - LDAP_AUTH_TLS=
      - LDAP_AUTH_BASE_DN="dc=ldap,dc=goauthentik,dc=io"
```

While I am able to bind the user with the following command:

```
ldapsearch \
  -x \
  -H ldap://auth.busybox.synology.me:50061 \
  -D 'cn=kaichen,ou=users,dc=ldap,dc=goauthentik,dc=io' \
  -w 'jlhkb0zPb7lczF' \
  -b 'dc=ldap,dc=goauthentik,dc=io'
```

I'm not able to login cypht with the same username and password, as the following screenshot:

![Image](https://github.com/user-attachments/assets/7e4e1071-acba-4b28-90f6-9c3863473e66)

And from my ldap server's (authentik ldap outpost) log, it seems that cypht is not reaching out to ldap server. Is there an example about how to config cyptht to login with ldap server?
