### ISSUE TITLE
🐛 [Bug] Cannot login when SESSION_TYPE=REDIS

### ISSUE THREAD

**Issue by diogovalentte** [cypht-org/cypht#1556]
## 🐛 Bug
When I set `SESSION_TYPE` to `REDIS` and try to login, it says that my credentials are wrong. Setting it to `DB` works, but it seems cypht doesn't use redis for caching.

I tested and the cypht container can connect to the redis container.

### Version & Environment
Using docker compose:
```yml
services:
  db:
    container_name: cypht-db
    image: mariadb:10
    volumes:
      - /Apps/cypht/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cypht_password
    restart: unless-stopped

  redis:
    container_name: cypht-redis
    image: redis:7-alpine
    volumes:
      - /Apps/cypht/redis/data:/data
    restart: unless-stopped

  cypht:
    container_name: cypht
    image: cypht/cypht:2.4.0
    volumes:
      - /Apps/cypht/users:/var/lib/hm3/users
    ports:
      - 46185:80
    environment:
      - DEBUG_LOG=true
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DB_CONNECTION_TYPE=host
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_NAME=cypht
      - DB_USER=cypht
      - DB_PASS=cypht_password
      - DB_SOCKET=/var/lib/mysqld/mysqld.sock
      - USER_CONFIG_TYPE=DB
      - SESSION_TYPE=REDIS
      - AUTH_TYPE=DB
      - ENABLE_REDIS=true
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - REDIS_INDEX=1
      - REDIS_SOCKET=
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_CLIENT_URI=${GMAIL_CLIENT_URI}
    restart: unless-stopped
```

### Logs
```
Attempting to connect to database ... (1/10)

Attempting to connect to database ... (2/10)

Database connection successful ...

Creating database table hm_user ...

CREATE TABLE IF NOT EXISTS hm_user (username varchar(255), hash varchar(255), primary key (username));

Creating database table hm_user_settings ...

Db setup finished

Creating directory for attachments /var/lib/hm3/attachments

user <redacted> already exists

scanning module core ...

scanning module contacts ...

scanning module local_contacts ...

scanning module ldap_contacts ...

scanning module gmail_contacts ...

scanning module feeds ...

scanning module jmap ...

scanning module imap ...

scanning module smtp ...

scanning module account ...

scanning module idle_timer ...

scanning module desktop_notifications ...

scanning module calendar ...

scanning module themes ...

scanning module nux ...

scanning module developer ...

scanning module profiles ...

scanning module imap_folders ...

scanning module sievefilters ...

site.css file created

site.js file created

dynamic.php file written

creating production site

2025-06-21 21:22:03,319 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.

2025-06-21 21:22:03,323 INFO supervisord started with pid 19

2025-06-21 21:22:04,325 INFO spawned: 'nginx' with pid 20

2025-06-21 21:22:04,326 INFO spawned: 'php-fpm' with pid 21

[21-Jun-2025 21:22:04] NOTICE: fpm is running, pid 21

[21-Jun-2025 21:22:04] NOTICE: ready to handle connections

2025-06-21 21:22:05,408 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

2025-06-21 21:22:05,408 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs
```
