### ISSUE TITLE
Declarative config for multiple accounts

### ISSUE THREAD

**Issue by jonocodes** [cypht-org/cypht#974]
## 💬 Question

First off, thanks for this app. I'm very happy to have found it, as it fits the needs I am looking for on my new server.

I have about 10 IMAP accounts. I would like to set them up with a config file instead of using the UI. It looks like this can be done for only a single IMAP server via env var IMAP_AUTH_*.

Is there a recommended way to do this? Perhaps set it up once and use USER_CONFIG_TYPE=file
then copy that file to my new system?

Side note I am running this in NixOS which I only mention because declarative configs are the norm there.

**Comment by marclaporte** [comment]
Thank you for the kind words.

Related: https://github.com/cypht-org/cypht/issues/470

For .env, let's ask the author @Shadow243 for some advice.

**Comment by jonocodes** [comment]
Where are the imap creds stored now? I was not able to quickly find them. I saw there were some blobs in the mysql db. There?

**Comment by Shadow243** [comment]
> > Thank you for the kind words.
> > Related: #470
> > For .env, let's ask the author @Shadow243 for some advice.
> 
> IMAP_AUTH_ is primarily used when AUTH_TYPE=IMAP to authenticate during the connection (on the login page) and of course to automatically add the server once connected.
> 
> Configuring multiple accounts via .env will complicate this file, but I think we can do it through a configuration file, as we did for LDAP Contact (config/ldap.php).
> 
> ```
> 'imap_accounts' => [
>     'Personal' => [
>         'server'  => '',
>         'port' => '',
>         'tls' => '',
>         'sieve' => '',
>         'username' => '',
>         'pwd' => ''
>     ],
>     'OtherName' => [
>         'server'  => '',
>         'port' => '',
>         'tls' => '',
>         'sieve' => '',
>         'username' => '',
>         'pwd' => ''
>     ],
> ]
> ```
> 
> This could allow us to anticipate the accounts (servers) to add on the server page automatically while retaining the IMAP_AUTH_ functionality with its initial function.

However, this scenario does not work in all cases. For example, we may have 10 IMAP accounts, but each account belongs to a different person. Therefore, each person must log in with their own account. By putting the accounts in the configuration file, everyone who is logged in will have access. However, this works in the case of someone managing (centralizing) his accounts in one place for himself

**Comment by jonocodes** [comment]
@Shadow243 my goal is to use the unified inbox with all these accounts, so no separate logins.

**Comment by marclaporte** [comment]
@jonocodes Will more than one person use your Cypht instance?

**Comment by jonocodes** [comment]
> @jonocodes Will more than one person use your Cypht instance?

My current use of cypht is much like how I use Thunderbird. I have a single profile/user. I use thunderbird to access all my accounts when at my main desktop. And I use a selfhosted cypht to access all my email accounts when I am away from my desktop.

**Comment by marclaporte** [comment]
Ok so then the .env should work for you. Please let us know how it goes.

**Comment by jonocodes** [comment]
> Ok so then the .env should work for you. Please let us know how it goes.

I don't think I understand. Are you saying the env file ready supports this? Or that I should develop that support? My understanding is it does not support it now.

**Comment by marclaporte** [comment]
@Shadow243 wrote: "However, this works in the case of someone managing (centralizing) his accounts in one place for himself"

So please try and let us know :-)

**Comment by Shadow243** [comment]
> @Shadow243 wrote: "However, this works in the case of someone managing (centralizing) his accounts in one place for himself"
> 
> 
> 
> So please try and let us know :-)

I'm now working on a good way to handle this even with multiple users.

**Comment by kroky** [comment]
> Is there a recommended way to do this? Perhaps set it up once and use USER_CONFIG_TYPE=file then copy that file to my new system?

Both config storage options would work - file or db as long as you copy the file or db to your new system and use the same user password for your account login to cypht (password is used as an encryption key for the data stored in local file or db). To keep things simpler, I suggest you use file storage for config and copy your user settings dir to the new system.

Mixing user configuration with system configuration from env or config php files might get tricky here...

**Comment by jonocodes** [comment]
I am trying to understand the file storage option. I ran this


```
version: '3'
services:
  db:
    image: mariadb:10
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cypht_password
  cypht:
    image: sailfrog/cypht-docker:latest
    volumes:
      - ./cypht/users:/var/lib/hm3/users
    ports:
      - "81:80"
    environment:
      - CYPHT_AUTH_USERNAME=admin
      - CYPHT_AUTH_PASSWORD=admin_password
      - CYPHT_DB_CONNECTION_TYPE=host
      - CYPHT_DB_HOST=db
      - CYPHT_DB_NAME=cypht
      - CYPHT_DB_USER=cypht
      - CYPHT_DB_PASS=cypht_password
      - CYPHT_SESSION_TYPE=DB
      - CYPHT_USER_CONFIG_TYPE=file

```

Then logged in and created some imap accounts. Now here is what the file system looks like:

```
/var/lib/hm3 # ls -lR
.:
total 3
drwxr-xr-x    2 www-data www-data         2 Apr 26 18:35 app_data
drwxr-xr-x    2 www-data www-data         2 Apr 26 18:35 attachments
drwxr-xr-x    2 www-data www-data         3 Apr 26 18:36 users

./app_data:
total 0

./attachments:
total 0

./users:
total 5
-rw-r--r--    1 www-data www-data      2716 Apr 26 19:41 admin.txt

```

of course admin.txt is giberish. Is this the encrypted payload that has all the imap credentials in it? And if so, is there a manual way for me to decrypt it outside cypht and see whats there?
